// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	OwnerID     pgtype.UUID      `json:"owner_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ProjectMember struct {
	ProjectID pgtype.UUID      `json:"project_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Role      string           `json:"role"`
	JoinedAt  pgtype.Timestamp `json:"joined_at"`
}

type Task struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Status      string           `json:"status"`
	ProjectID   pgtype.UUID      `json:"project_id"`
	AssigneeID  pgtype.UUID      `json:"assignee_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
