// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING project_id, user_id, role, joined_at
`

type AddMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getProjectMembers = `-- name: GetProjectMembers :many
SELECT u.id, u.username, u.email, pm.role, pm.joined_at
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
`

type GetProjectMembersRow struct {
	ID       pgtype.UUID      `json:"id"`
	Username string           `json:"username"`
	Email    string           `json:"email"`
	Role     string           `json:"role"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

func (q *Queries) GetProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]GetProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, getProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectMembersRow
	for rows.Next() {
		var i GetProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (
    SELECT 1 FROM project_members
    WHERE project_id = $1 AND user_id = $2
) AS is_member
`

type IsMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.ProjectID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.ProjectID, arg.UserID)
	return err
}
